// <auto-generated />
using System;
using BebidasStore.DbContextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BebidasStore.Migrations
{
    [DbContext(typeof(BebidasStoreContexto))]
    [Migration("20210915192609_PrimeiraMigracao")]
    partial class PrimeiraMigracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BebidasStore.Entidades.Bebida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("MarcaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Bebidas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("375c6026-2679-40e3-aa95-141745dcd409"),
                            Descricao = "Bebida gasificada sabor fruta guaraná sem adição de açúcar.",
                            MarcaId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Nome = "Guaraná Zero Açúcar"
                        },
                        new
                        {
                            Id = new Guid("1cfce5f9-c095-4bc7-9bb8-f0f7d81a5909"),
                            Descricao = "Bebida gasificada sabor fruta guaraná.",
                            MarcaId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Nome = "Guaraná"
                        },
                        new
                        {
                            Id = new Guid("abeb730f-3d6c-441c-85c5-480b85b960c5"),
                            Descricao = "Água gasificada sabor laranja & limão com baixa caloria.",
                            MarcaId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Nome = "H20 Laranja & Limão"
                        },
                        new
                        {
                            Id = new Guid("5dbdf830-9194-40df-a859-0d9289bed798"),
                            Descricao = "Água gasificada sabor uva com baixa caloria.",
                            MarcaId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Nome = "H20 Uva"
                        },
                        new
                        {
                            Id = new Guid("eb1b5d4f-5990-4015-bc48-98c0a322490c"),
                            Descricao = "Bebida gasificada sem adição de açúcar.",
                            MarcaId = new Guid("dea22bcd-a2fa-40a0-b559-d4adcc981620"),
                            Nome = "Pepsi Zero Açúcar"
                        },
                        new
                        {
                            Id = new Guid("79e2aa60-4cc8-46d7-bac6-cf303251a981"),
                            Descricao = "Bebida gasificada.",
                            MarcaId = new Guid("dea22bcd-a2fa-40a0-b559-d4adcc981620"),
                            Nome = "Pepsi"
                        },
                        new
                        {
                            Id = new Guid("18c1cf49-3de2-44c1-8a7e-0d54fd7aade0"),
                            Descricao = "Isotonico sabor limão.",
                            MarcaId = new Guid("738ab439-da32-4ac5-9fc1-d614ecb0a3a5"),
                            Nome = "Gatorade Limão"
                        },
                        new
                        {
                            Id = new Guid("ad005f9d-a407-4015-a07b-78242a9d0a25"),
                            Descricao = "Isotonico sabor maracujá.",
                            MarcaId = new Guid("738ab439-da32-4ac5-9fc1-d614ecb0a3a5"),
                            Nome = "Gatorade Maracujá"
                        });
                });

            modelBuilder.Entity("BebidasStore.Entidades.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Industria")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Industria = "Pepsico",
                            Nome = "Guaraná Antarctica"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Industria = "Pepsico",
                            Nome = "H20"
                        },
                        new
                        {
                            Id = new Guid("dea22bcd-a2fa-40a0-b559-d4adcc981620"),
                            Industria = "Pepsico",
                            Nome = "Pepsi"
                        },
                        new
                        {
                            Id = new Guid("738ab439-da32-4ac5-9fc1-d614ecb0a3a5"),
                            Industria = "Pepsico",
                            Nome = "Gatorade"
                        });
                });

            modelBuilder.Entity("BebidasStore.Entidades.Bebida", b =>
                {
                    b.HasOne("BebidasStore.Entidades.Marca", "Marca")
                        .WithMany("Bebidas")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
